// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoSetupShootHighGoalCmdGrp.h"
#include "AutoThroughDefenseCmdGrp.h"
#include "DriveStraightCmd.h"
#include "DrivePointTurnCmd.h"
#include "LiftToAngleCmd.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoSetupShootHighGoalCmdGrp::AutoSetupShootHighGoalCmdGrp() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

	AddSequential(new AutoThroughDefenseCmdGrp());

	AddParallel(new LiftToAngleCmd(40.5,0));				// 40 degrees
	AddSequential(new DriveStraightCmd(0.6, 75.5 , 8, 1)); 	// 75.5 inches 4 inches short because of stopping overrun															// mode 1=Yes Gyro Assist

	AddSequential(new DrivePointTurnCmd(58, 0.5, 7, 0));	// 60 degree turn, 0.5 speed, 7 sec TO, mode 0=standard
	AddSequential(new DriveStraightCmd(0.6, 12 , 8, 1)); 	// 24 inches to get to 8 feet from tqrget




}
