// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DelayCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DelayCmd::DelayCmd(double time): Command() {
    m_time = time;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DelayCmd::Initialize() {
	SetTimeout(m_time);						// we should hit bottom within 10 seconds
}

// Called repeatedly when this Command is scheduled to run
void DelayCmd::Execute() {
	// this just wait for time out to occur
}

// Make this return true when this Command no longer needs to run execute()
bool DelayCmd::IsFinished() {
	if (IsTimedOut()) return true;
    return false;
}

// Called once after isFinished returns true
void DelayCmd::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DelayCmd::Interrupted() {

}
