// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShooterHoldBallCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterHoldBallCmd::ShooterHoldBallCmd(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterSys.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterHoldBallCmd::Initialize() {
	Robot::shooterSys->HoldBall();
}

// Called repeatedly when this Command is scheduled to run
void ShooterHoldBallCmd::Execute() {
	Robot::shooterSys->DisplaySmartdashValues();
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterHoldBallCmd::IsFinished() {
	if (Robot::shooterSys->GetRearContactLmtSw() == false)			// no ball so get out
		return true;
	else
		return false;
}

// Called once after isFinished returns true
void ShooterHoldBallCmd::End() {
	Robot::shooterSys->StopRearMtr();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterHoldBallCmd::Interrupted() {
	End();
}
