// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShooterSetTargetSpeedCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterSetTargetSpeedCmd::ShooterSetTargetSpeedCmd(double speed): Command() {
    m_speed = speed;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterSetTargetSpeedCmd::Initialize() {
	if (m_speed == 0)
		Robot::shooterSys->SetShooterSpeed(Robot::shooterSys->kShootHiGoalSpeed);
	if (m_speed == 1)
		Robot::shooterSys->SetShooterSpeed(Robot::shooterSys->kShootLowGoalSpeed);

}

// Called repeatedly when this Command is scheduled to run
void ShooterSetTargetSpeedCmd::Execute() {
	Robot::shooterSys->DisplaySmartdashValues();
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterSetTargetSpeedCmd::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ShooterSetTargetSpeedCmd::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterSetTargetSpeedCmd::Interrupted() {
	End();
}
