// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "VisionLaserCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

VisionLaserCmd::VisionLaserCmd(bool onFlag): Command() {
    m_onFlag = onFlag;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lEDRingSys.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void VisionLaserCmd::Initialize() {
	if (m_onFlag)
		Robot::lEDRingSys->SetLaser(true);
	else
		Robot::lEDRingSys->SetLaser(false);

}

// Called repeatedly when this Command is scheduled to run
void VisionLaserCmd::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool VisionLaserCmd::IsFinished() {
    return true;					// we just need to run once ... initialize and get out
}

// Called once after isFinished returns true
void VisionLaserCmd::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void VisionLaserCmd::Interrupted() {

}
