// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> drivetrainLeftMtr;
	static std::shared_ptr<SpeedController> drivetrainRightMtr;
	static std::shared_ptr<RobotDrive> drivetrainRobotDrive2;
	static std::shared_ptr<Encoder> drivetrainDriveLeftEncoder;
	static std::shared_ptr<Encoder> drivetrainDriveRightEncoder;
	static std::shared_ptr<AnalogGyro> drivetrainGyroA;
	static std::shared_ptr<AnalogInput> drivetrainMaxSonar;
	static std::shared_ptr<AnalogInput> drivetrainProxSensor;
	static std::shared_ptr<SpeedController> liftSysLiftMtr;
	static std::shared_ptr<Encoder> liftSysLiftEncoder;
	static std::shared_ptr<DigitalInput> liftSysLiftUpLmtSw;
	static std::shared_ptr<DigitalInput> liftSysLiftLoLmtSw;
	static std::shared_ptr<AnalogInput> liftSysLiftPot;
	static std::shared_ptr<SpeedController> shooterSysShooterFrontMtr;
	static std::shared_ptr<SpeedController> shooterSysShooterRearMtr;
	static std::shared_ptr<DigitalInput> shooterSysShooterContactSw;
	static std::shared_ptr<Relay> shooterSysCaptureLeftSpike;
	static std::shared_ptr<Relay> shooterSysCaptureRightSpike;
	static std::shared_ptr<Relay> lEDRingSysLEDSpike;
	static std::shared_ptr<Relay> smartdashRobotLightsSpike;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
